### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by illustree** [laresgoiti/texts_translate#1]
“change locale” crashes Sketch ... no functionality atm ... Sketch v43.1

Besides that a very nice idea and a really needed thing ... I would love to have it in my daily workflow.
thx for fixing and improving!

**Comment by laresgoiti** [comment]
@illustree have you made any action before (as save current locale) that error?

**Comment by bomberstudios** [comment]
We're getting a few crash reports on our side, related to `[NSFileManager createDirectoryAtPath:withIntermediateDirectories:attributes:error:]`, in case that helps.

**Comment by bomberstudios** [comment]
Basically, from a fresh install of the plugin (i.e: never used it before on this machine), just open a document and choose 'Change Locale'. Sketch will crash immediately.

**Comment by illustree** [comment]
@laresgoiti I actually just created a new document ... added a couple of text fields and saved the document ... then ran the plugin and crashed

**Comment by laresgoiti** [comment]
@bomberstudios @illustree before launch I tested cases like this and it worked for me, there are some [checks](https://github.com/laresgoiti/texts_translate/commit/38d1736183240372a15e2dd59bb0eedacbd7d30f#diff-9036c5a0f7e7b81268a47e93197ca762R277) before these actions, but something seems to be wrong when creating the folder. I've tried in my computer and I've replicated this error, so I'll work in solve this. Hope I have a solution soon, thanks for reporting this!

**Comment by laresgoiti** [comment]
Not solved yet.

Confusing, I've tested in same sketch document where I created README gif and is failing (with last commit I've resolved crashing issue to at least show error message):
![screen shot 2017-04-20 at 23 18 09](https://cloud.githubusercontent.com/assets/7079748/25253200/277bfe48-2620-11e7-9e6d-dc6b98fa9709.png)

It seems like there is a problem with fileManager when trying to check if folder exists or creating:
![screen shot 2017-04-20 at 23 19 07](https://cloud.githubusercontent.com/assets/7079748/25253201/27967c00-2620-11e7-8a64-7c429e2d2cf1.png)

Any ideas?

I'll keep working on this.

**Comment by laresgoiti** [comment]
@bomberstudios in <code>Run Custom Script</code> mode, I've tested the following lines and I'm having an unexpected behaviour:
```
var document = context.document
var documentName = document.displayName()
var documentFolderPath = decodeURIComponent(document.fileURL()).replace('file:///','').replace(documentName,"")

print(documentName)
print(documentFolderPath)

var translationsFolderName = documentName.replace('.sketch','_translations')
var translationsFolderPath = documentFolderPath+translationsFolderName+'/'

print(translationsFolderName)
print(translationsFolderPath)

var fileManager = [NSFileManager defaultManager]

if(![fileManager fileExistsAtPath:translationsFolderPath isDirectory:'YES'])
{
   print(translationsFolderPath+" folder does not exist")
   if(![fileManager createDirectoryAtPath:translationsFolderPath withIntermediateDirectories:'YES' attributes:nil error:nil])
    {
       print(translationsFolderPath+" folder can't be created")
    }
}
```
result:
```
test.sketch
Users/whatever/Documents/
test_translations
Users/whatever/Documents/test_translations/
Users/whatever/Documents/test_translations/ folder does not exist
Users/whatever/Documents/test_translations/ folder can't be created

Script executed in 0.028599s
```

This part of the code has been working in other Sketch versions, I don't know why is crashing now, any idea?

**Comment by iliakukharev** [comment]
43.2 also crashing
still no ideas?

**Comment by laresgoiti** [comment]
Still blocked with <code>fileManager</code> issue, as described [above](https://github.com/laresgoiti/texts_translate/issues/1#issuecomment-296440096).

Unexpected response from:
- <code>fileExistsAtPath</code> return 'folder does not exist' when actually exists in that path
- <code>createDirectoryAtPath</code> return 'error' when trying to create a non-existing folder

This worked in versions before.

Working in fix or alternatives.

**Comment by laresgoiti** [comment]
fixed, not crashing in 43

/cc @illustree @bomberstudios @iliakukharev
