### ISSUE TITLE
Translation files are placed in hidden folders

### ISSUE THREAD

**Issue by keppes** [laresgoiti/texts_translate#8]
If a sketch files doesn't have an extension (which happens automatically) the generated folder will have .sketch added at the beginning of the filename. This causes the folder to become hidden.

https://www.dropbox.com/s/rt997q6hg2xsbr5/Screenshot%202017-06-16%2016.00.59.png?dl=0
-> the file with the .sketch extension generates the correct folder.

**Comment by laresgoiti** [comment]
Done in #13 

There is no retrocompatibility, move your translated files from hidden folders to correct folder.
